ibeo_8l_client:
  ibeo_file_sim:
    ros__parameters:
      idc_file: "/home/tom/ibeo_ws/src/ibeo_8l_client/record/20190320-085450.idc"

  obj_visualization:
     ros__parameters:
        ibeo_object_topic: "/object_tracker/ibeo_objects_retrack"

object_tracker:
  object_tracker:
    ros__parameters:
      scan_cloud_topic: "/ibeo_8l_client/ibeo_scan_up"
      odom_sub_topic: "/ibeo_8l_client/vehicle_odom"
