ibeo_8l_client:
  ibeo_live:
    ros__parameters:
      ip: "192.168.2.16"
      port: 12002

  obj_visualization:
     ros__parameters:
        ibeo_object_topic: "/object_tracker/ibeo_objects_retrack"


object_tracker:
  object_tracker:
    ros__parameters:
      scan_cloud_topic: "/ibeo_8l_client/ibeo_scan_up"
      odom_sub_topic: "/ibeo_8l_client/vehicle_odom"